ewz_recaptcha:
  public_key: '%env(GOOGLE_RECAPTCHA_SITE_KEY)%'
  private_key: '%env(GOOGLE_RECAPTCHA_SECRET)%'
  # Not needed as "%kernel.default_locale%" is the default value for the locale key
  locale_key:  '%kernel.default_locale%'
  locale_from_request: true